# docker-compose.yml
version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - localhost

  localhost:
    image: postgres:latest
    environment:
      POSTGRES_DB: myblog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: it@12345
    ports:
      - "5432:5432"
