# docker-compose.yml

version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myblog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: it@12345
    restart: always # Add this line to enable automatic restart
